name: Deploy to GitHub Pages Repo

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to public repo
        uses: cpina/github-action-push-to-another-repository@v1.8.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAGES_TOKEN }}
        with:
          source-directory: "."
          destination-github-username: "alexzalox"
          destination-repository-name: "alexzalox.github.io-public"
          target-branch: "main"